name: Code checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
      PYTHONIOENCODING: UTF-8


jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ matrix.os }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Run FirstStep test
        run: python -m unittest test_module1
